### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by gilesknap** [MARCTR0N/Transformers-Mod#4]
Apologies for a newby question but I dont not know how to install this. My son is very keen to give this a go but I've let him down!

I have successfully installed forge and other mods but this I can't get to work.

I cannot see any instructions, I guess it is assumed that mod installers know what to do?

Thanks,
giles.

**Comment by ImranDoet** [comment]
Hi giles, 

Nice to see that your son is interested in the mod! The mod is up on curseforge: https://www.curseforge.com/minecraft/mc-mods/transformers-unlimited. Download the jar from there and drag it into the mods folder like any other mod!

Imran.

**Comment by gilesknap** [comment]
Thanks for the quick reply.
My steps were:
- launch the launcher
- Create a new installation and choose 1.12.2 version
- launch the new version and create a new world in creative mode
- exit and copy your jar into ~/.minecraft/mods
- re-launch and go into inventory and search for 'trans'
- see no items other than standard

I'm running on Linux if that makes a difference.

What did I do wrong in the above?

Thanks!

**Comment by ImranDoet** [comment]
Could you please run the game again, going to ~/.minecraft/logs and send us the latest.log file? In a paste bin or just as attachment here on this issue.

**Comment by MARCTR0N** [comment]
Running the latest version of forge 1.12.2 and having the mod in the mods folder works for me.
I don't believe the operating system should make a difference.

**Comment by MARCTR0N** [comment]
Are you certain that you have launched the correct version of forge in the client?

**Comment by gilesknap** [comment]
Thanks, I got this to work. Noah is delighted.

I think I had confusion over mixed versions of Minecraft and forge
installed.

The next question is do you have any documentation on how to play the mod?
The only info I can find is  'X and Y to transform' and that does not
appear to work on Noah's character which he has managed to dress up as
Optimus.

It seems like there is intended to be interesting game mechanics around
energon etc. but I am at a loss to work out what they are.

I am bemused by the lack of documentation on all the mods we have tried so
I must be missing something? Is there some tacit knowledge that we
are missing? :-)

Thanks for taking the time to answer newbie qs.

**Comment by MARCTR0N** [comment]
The mod is still in development, the currently public available version has some unfinished content, documentation will arrive once the next update comes out

**Comment by gilesknap** [comment]
Awesome. Thanks again.
